diff_drive_controller:
  ros__parameters:
    type: "diff_drive_controller/DiffDriveController"
    left_wheel_names: ["left_front_wheel_joint", "left_rear_wheel_joint"]
    right_wheel_names: ["right_front_wheel_joint", "right_rear_wheel_joint"]
    wheel_separation: 0.4
    wheel_radius: 0.1
    cmd_vel_timeout: 0.5
    enable_odom_tf: true
    publish_rate: 50
    odom_frame_id: "odom"
    base_frame_id: "base_link"
    velocity_rolling_window_size: 10
    open_loop: false
